# Generated by Django 4.1.7 on 2023-03-28 12:04

from django.db import migrations, models
import django.utils.timezone
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="application_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scholarship_id", models.IntegerField(default=0)),
                ("user_id", models.IntegerField(default=0)),
                ("status", models.IntegerField(blank=True, default=2, null=True)),
                (
                    "your_name",
                    models.CharField(
                        blank=True, default="myname", max_length=20, null=True
                    ),
                ),
                ("your_num", models.IntegerField(default=122159104)),
                ("your_id_num", models.IntegerField(default=0)),
                ("date_of_birth", models.DateField(default=django.utils.timezone.now)),
                ("gender", models.CharField(default="", max_length=20)),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary School"),
                            ("highschool", "High School"),
                            ("college", "College"),
                            ("university", "University"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("school_name", models.CharField(default="n/a", max_length=20)),
                (
                    "addmission_number",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("campus_branch", models.CharField(default="muranga", max_length=25)),
                ("faculty", models.CharField(default="", max_length=20)),
                ("course_of_study", models.CharField(default="", max_length=20)),
                ("mode_of_study", models.CharField(default="", max_length=30)),
                ("year_of_study", models.CharField(default="", max_length=20)),
                ("academic_year", models.CharField(default=0, max_length=10)),
                ("course_duration", models.IntegerField(default=0)),
                ("year_of_completion", models.IntegerField(default=0)),
                ("physical_address", models.CharField(default="", max_length=20)),
                ("location", models.CharField(default="", max_length=20)),
                ("sub_location", models.CharField(default="", max_length=20)),
                ("ward", models.CharField(default="", max_length=20)),
                (
                    "institutions_postal_address",
                    models.CharField(default="", max_length=20),
                ),
                ("institutions_tel_no", models.CharField(default="", max_length=20)),
                ("amnt_applied_for", models.CharField(default="", max_length=20)),
                ("family_background", models.CharField(default="", max_length=30)),
                ("num_of_siblings", models.IntegerField(default=0)),
                ("sibling_name", models.CharField(default="", max_length=20)),
                (
                    "sibling_institution",
                    models.CharField(default="college", max_length=30),
                ),
                ("sibling_fee", models.IntegerField(default="0")),
                ("est_family_income", models.IntegerField(default=10000)),
                ("est_family_expenses", models.IntegerField(default=10000)),
                ("school_in_kenya", models.CharField(default="none", max_length=30)),
                (
                    "allocated_amnt",
                    models.CharField(default="", max_length=20, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                ("father_address", models.CharField(default="", max_length=20)),
                ("father_num", models.CharField(default="", max_length=20)),
                ("father_occupation", models.CharField(default="", max_length=20)),
                ("father_employment", models.CharField(default="", max_length=50)),
                ("father_main_income", models.CharField(default="", max_length=20)),
                (
                    "mother_name",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                ("mother_address", models.CharField(default="", max_length=20)),
                ("mother_num", models.CharField(default="", max_length=20)),
                ("mother_occupation", models.CharField(default="", max_length=20)),
                ("mother_employment", models.CharField(default="", max_length=50)),
                ("mother_main_income", models.CharField(default="", max_length=20)),
                (
                    "guardian_name",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                ("guardian_address", models.CharField(default="", max_length=20)),
                ("guardian_num", models.CharField(default="", max_length=20)),
                ("guardian_occupation", models.CharField(default="", max_length=20)),
                ("guardian_employment", models.CharField(default="", max_length=50)),
                ("guardian_main_income", models.CharField(default="", max_length=20)),
                (
                    "applied_student_id",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/student_id"
                    ),
                ),
                (
                    "applied_father_id",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/father_id"
                    ),
                ),
                (
                    "applied_document_last_sem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/document_last_sem",
                    ),
                ),
                (
                    "applied_document12",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/document12"
                    ),
                ),
                (
                    "applied_document10",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/document10"
                    ),
                ),
                (
                    "applied_extra1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/extra1",
                        validators=[homepage.models.file_size],
                    ),
                ),
                (
                    "applied_extra2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/extra2",
                        validators=[homepage.models.file_size],
                    ),
                ),
                (
                    "applied_scholarship_form",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="applications/applied_scholarship_form",
                        validators=[homepage.models.file_size2],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("short_description", models.CharField(max_length=100)),
                ("long_description", models.TextField()),
                (
                    "img",
                    models.ImageField(
                        default="pics/scholarship_pics/default.png",
                        upload_to="pics/scholarship_pics",
                        validators=[homepage.models.file_size],
                    ),
                ),
                ("both", models.IntegerField(blank=True, default=0, null=True)),
                ("boy", models.IntegerField(blank=True, default=-1, null=True)),
                ("girl", models.IntegerField(blank=True, default=-1, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "document",
                    models.FileField(
                        upload_to="documents/scholarship_broucher/",
                        validators=[homepage.models.file_size2],
                    ),
                ),
                (
                    "scholarship_form",
                    models.FileField(
                        default="documents/scholarship_form/default_scholarship_form.pdf",
                        upload_to="documents/scholarship_form/",
                        validators=[homepage.models.file_size2],
                    ),
                ),
                ("fromdate", models.DateField(null=True)),
                ("toomdate", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="session_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0)),
                ("scholarship_id", models.IntegerField(default=0)),
                ("session", models.IntegerField(default=0)),
            ],
        ),
    ]
